name: doxygen-github-pages

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install doxygen
        run: sudo apt install doxygen graphviz fonts-freefont-ttf
      - name: Build html docs
        run: make doxygen && cp -R .circleci docs/html/
      - name: Deploy gh-pages
        uses: JamesIves/github-pages-deploy-action@3.5.7
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/html
          SINGLE_COMMIT: true
